name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: -> # optional
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_LOC_CHART: false
          SHOW_LANGUAGE_PER_REPO: true
          IGNORED_REPOS: "github-stats, 42-project-badges"
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          COMMIT_BY_ME: true
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          AUTHOR_NAME: Ana Alejandra Castillejo # optional
          AUTHOR_EMAIL: yo@anaalejandra.com # optional